version: "3.8"


services:
  
  frontend:
    container_name: image-processor-frontend
    build:
      context: ./Frontend_react 
    ports:
      - 3000:3000
    
    depends_on:
      - backend

  backend:
    container_name: image-processor-backend
    build:
      context: ./Backend/my_project
    ports:
      - 5001:5001
    
      
  